
version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: member-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=nodejs
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=trieu
      - MYSQL_PASSWORD=password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5
    ports:
      - '5050:3306'
    networks:
      - shared-network
    expose:
      - 3306
  backend:
    container_name: backend_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - TZ= UTC
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - shared-network
networks:
  shared-network:
