const router = require('express').Router()
const pollController = require('../controllers/pollController')
const asyncHandler = require('express-async-handler')
const { verifyToken } = require('../middleware/verifyToken')
router.post('/create-poll', [verifyToken], asyncHandler(pollController.createPoll))
router.put('/update-poll/:pollId', [verifyToken],asyncHandler(pollController.updatePoll))
router.put('/update-poll/options/:optionId', asyncHandler(pollController.updateOption))
router.post('/update-poll/add-options/:pollId', [verifyToken], asyncHandler(pollController.addOption))
router.delete('/update-poll/delete-option/:optionId', [verifyToken],asyncHandler(pollController.deleteOption))
router.delete('/delete-poll/:pollId', [verifyToken], asyncHandler(pollController.deletePoll))
router.get('/get-poll/:pollId', [verifyToken], asyncHandler(pollController.getPoll))
router.get('/submit-vote/:optionId', [verifyToken], asyncHandler(pollController.submit))
router.get('/unsubmit-vote/:optionId', [verifyToken], asyncHandler(pollController.unsubmit))
module.exports = router